FROM ubuntu:latest

RUN apt-get update 
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y python-numpy python-matplotlib

COPY newton_binomial.py .

ENTRYPOINT [ "python3", "newton_binomial.py" ]
